apiVersion: v1
kind: Pod
metadata:
  name: app-resource
spec:
  containers:
  - name: app-resource
    image: gcr.io/daring-sunset-384809/demo:v1.0.0
    ports:
    - containerPort: 8080
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 128Mi
    livenessProbe:
      httpGet:
        path: /
        port: 8080
    readinessProbe:
      httpGet:
        path: /
        port: 8080
  imagePullSecrets:
  - name: myregistrykey