apiVersion: v1
kind: Pod
metadata:
  name: app-volume
spec:
  containers:
   - name: app-volume
     image: gcr.io/daring-sunset-384809/demo:v1.0.0
     ports:
     - containerPort: 8080
       volumeMounts:
     - name: app-volume
       mountPath: /data
  volumes:
  - name: app-volume
    emptyDir: {}
  livenessProbe:
    httpGet:
      path: /
      port: 8080
  readinessProbe:
    httpGet:
      path: /
      port: 8080