---
apiVersion: v1
kind: Pod
metadata:
  name: app
  labels: 
    app: demo
    run: demo
spec:
  containers:
    - image: debian
      name: app
      ports:
        - containerPort: 8000
          name: http